{"name": "Тест если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Передаем несуществующий логин, пароль проверяем код 404 и что телоответа содержит \"Недостаточно данных для входа\"", "parameters": [{"name": "login", "value": "'nonexistent_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1709910513830, "stop": 1709910514062, "uuid": "227d0313-0525-4232-a5ea-54c3dbaad50e", "historyId": "9e60c7318c4ba76840e32a5ef970b4ce", "testCaseId": "13b58fa1aaf6b382c386cbb5e82acef8", "fullName": "tests.test_login_couriers.TestLoginCouriers#test_authentication_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_couriers"}, {"name": "subSuite", "value": "TestLoginCouriers"}, {"name": "host", "value": "LAPTOP-4KULGNVQ"}, {"name": "thread", "value": "10584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_couriers"}]}