{"name": "Тест если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Передаем несуществующий логин, пароль проверяем код 404 и что телоответа содержит \"Недостаточно данных для входа\"", "parameters": [{"name": "login", "value": "'nonexistent_user'"}, {"name": "password", "value": "'1234'"}], "start": 1709910513591, "stop": 1709910513826, "uuid": "3d74d653-3093-4e4c-8490-8abacc93bd1f", "historyId": "b957967cfec82cfe27069feb738013fc", "testCaseId": "13b58fa1aaf6b382c386cbb5e82acef8", "fullName": "tests.test_login_couriers.TestLoginCouriers#test_authentication_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_couriers"}, {"name": "subSuite", "value": "TestLoginCouriers"}, {"name": "host", "value": "LAPTOP-4KULGNVQ"}, {"name": "thread", "value": "10584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_couriers"}]}